### ISSUE TITLE
Not 

### ISSUE THREAD

**Issue by skribbleuk** [Prince25/StockAlertBot#129]
Getting continuous 403 errors from Ebuyer UK, independent of whether I use proxies or not (currys and amazon scrape fine).

Error: 403 - Forbidden
    at file:///C:/Users/Michael/Desktop/StockAlertBot-main/ebuyer/src/utils/fetch.js:106:11
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Item.getPage (file:///C:/Users/Michael/Desktop/StockAlertBot-main/ebuyer/src/item.js:23:20)
    at async Store.monitorItems (file:///C:/Users/Michael/Desktop/StockAlertBot-main/ebuyer/src/store.js:57:21)
ITEM_INFO: {
    "url": "https://www.ebuyer.com/1124532-asus-geforce-rtx-3070-8gb-dual-ampere-graphics-card-dual-rtx3070-8g",
    "notificationSent": false,
    "shouldSendNotification": true,
    "info": {}
}

could this be a headers problem?

**Comment by Prince25** [comment]
Could you please provide the files in the `logs` folder? It should be labeled something like `ebuyer.log` and `ebuyerHTML.log`.
